### ISSUE TITLE
Flag for merging in "pnpm" key from root package.json

### ISSUE THREAD

**Issue by tcandens** [Madvinking/pnpm-isolate-workspace#1]
First of all, thank you very much for publishing this. Just getting started with it but looks very promising for simplifying the creating of containers from workspaces.

One thing that I'm noticing that could be very useful is a flag that could automatically pluck out the PNPM config from a monorepo's root `package.json` (https://pnpm.io/package_json) and include it in the `package.json` and/or `package-prod.json` created within the `_isolated_` directory.

It could be argued that this is probably a good default behavior to include in the generation of any of the isolated package.json files but if we would prefer to use a flag to trigger this, how about something like `--include-root-config`?

I'd be happy to submit a PR so please let me know what you think.

Thanks

**Comment by Madvinking** [comment]
@tcandens sounds like u right.
didn't have time to work on this package lately.
I'll get back to maintain it
if u like to create the PR u are welcome to.
if not, i hope i will get to it next week or so.
