### ISSUE TITLE
npm ERR! Cannot read properties of null (reading 'package') on windows -- Package subpath './src/difference.js' is not defined by "exports" in /root/.npm/_npx/62cce0142d25c194/node_modules/@pnpm/prune-lockfile/node_modules/ramda/package.json

### ISSUE THREAD

**Issue by sebastiangug** [Madvinking/pnpm-isolate-workspace#13]
This doesn't work neither on linux or on windows throwing the errors in the title. 

Tried to use as part of a docker container, not really sure where to go from here.

**Comment by Madvinking** [comment]
yes for now u can downgrade to 0.0.6

**Comment by Madvinking** [comment]
will have a newer working version soon
@sebastiangug

**Comment by Madvinking** [comment]
@sebastiangug should be fine now in 0.0.8...

**Comment by sebastiangug** [comment]
Oh wow that was quick, nice!

**Comment by Madvinking** [comment]
sorry forgot to downgrade pnpm prune package as well 
0.0.9 is the good version
