### ISSUE TITLE
Support or infer `.` as workspace name or folder

### ISSUE THREAD

**Issue by DesignByOnyx** [Madvinking/pnpm-isolate-workspace#2]
It would be nice if running `npx pnpm-isolate-workspace` (without a workspace name) would attempt to infer the name from the current working directory. I would also be ok with requiring `.` as it is explicit and is already required by docker build.

```
npx pnpm-isolate-workspace . && docker build -t some-tag .
```

Thanks for such an awesome tool!!

**Comment by Madvinking** [comment]
published in 0.0.3
