### ISSUE TITLE
Workspace Dev Dependencies Not Being Included When Isolating

### ISSUE THREAD

**Issue by billdybas** [Madvinking/pnpm-isolate-workspace#7]
Thanks for this project! 

I've been trying to get it up & running in an existing monorepo, and I encountered what I think? is bug with nested `devDependencies` that rely on [`workspace:`](https://pnpm.io/workspaces#workspace-protocol-workspace) packages. 

While they're referenced in the `pnpm-lock.yaml` in the `_isolated_` directory, they're not copied over to the `workspaces` directory, so a `pnpm install --frozen-lockfile` fails w/ `Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date`.

I've put together an example w/ reproduction steps & possible workarounds to get the `pnpm install --frozen-lockfile` to succeed if that helps w/ identifying where the issue is.

https://github.com/billdybas/pnpm-isolate-workspace-bug

Let me know if you have any questions!

`pnpm-isolate-workspace` Version: 0.0.4
`pnpm` Version: 6.11.0

**Comment by TeChn4K** [comment]
Thanks a lot @billdybas for the workarounds :+1: 

On an other hand, what about generate a `pnpm-lock-prod.yaml`? Could be great to prevent Docker cache invalidation on dev deps change.

Gentle ping @Madvinking
